export const Design = {
  colors: {
    ink: '#2E3230',
    inkSoft: '#62685F',
    inkFaint: '#8A9087',
    background: '#FAF6F0',
    backgroundMuted: '#F0ECE4',
    surface: '#FFFFFF',
    surfaceRaised: '#FFFFFF',
    primary: '#4A7C59',
    primaryDark: '#2A6038',
    primarySoft: '#E7F1E8',
    lavender: '#DDEBDD',
    peach: '#F4E4D5',
    peachStrong: '#9A684D',
    sage: '#DCEBE2',
    sageStrong: '#467766',
    yellow: '#F8E4B8',
    accent: '#9A684D',
    accentSoft: '#F9EEE7',
    gold: '#8D6A2F',
    border: '#E4E0D8',
    borderStrong: '#CDC8BD',
    danger: '#B6514B',
    dangerSoft: '#FBE9E6',
    temperatureLow: '#E8F1F8',
    temperatureLowStrong: '#8AAEC7',
    temperatureNormal: '#E5F1E7',
    temperatureElevated: '#FAEDCF',
    temperatureFever: '#FBE6E2',
    temperatureFeverStrong: '#EBAFA9',
    shadow: '#334239',
  },
  fonts: {
    regular: 'Manrope_400Regular',
    medium: 'Manrope_500Medium',
    semiBold: 'Manrope_600SemiBold',
    bold: 'Manrope_700Bold',
    extraBold: 'Manrope_800ExtraBold',
  },
  type: {
    display: { fontSize: 32, lineHeight: 39, letterSpacing: -1.1 },
    title: { fontSize: 22, lineHeight: 28, letterSpacing: -0.45 },
    section: { fontSize: 18, lineHeight: 24, letterSpacing: -0.2 },
    body: { fontSize: 15, lineHeight: 22 },
    bodySmall: { fontSize: 13, lineHeight: 19 },
    caption: { fontSize: 12, lineHeight: 17 },
  },
  radius: {
    small: 14,
    medium: 19,
    large: 24,
    hero: 30,
    round: 999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  size: {
    input: 56,
    button: 54,
    iconSmall: 40,
    iconMedium: 48,
  },
  navigation: {
    tabBarHeight: 76,
    tabBarEdgeGap: 9,
    screenContentBottomPadding: 136,
  },
  shadow: {
    card: {
      shadowColor: '#334239',
      shadowOpacity: 0.06,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 8 },
      elevation: 1,
    },
    floating: {
      shadowColor: '#334239',
      shadowOpacity: 0.13,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
    },
  },
};
