export const Design = {
  colors: {
    ink: '#302D36',
    inkSoft: '#746F7A',
    inkFaint: '#9A949F',
    background: '#FBF8F5',
    backgroundMuted: '#F5F0EB',
    surface: '#FFFEFC',
    surfaceRaised: '#FFFFFF',
    primary: '#8478AA',
    primaryDark: '#625682',
    primarySoft: '#F0ECF7',
    lavender: '#E6DFF2',
    peach: '#F6DED5',
    peachStrong: '#C87968',
    sage: '#E2EEE8',
    sageStrong: '#5F897B',
    yellow: '#F5EACB',
    accent: '#C87968',
    accentSoft: '#FAECE7',
    gold: '#B68C43',
    border: '#EAE4DF',
    borderStrong: '#DCD4CE',
    danger: '#B65E54',
    dangerSoft: '#F9E9E6',
    shadow: '#4A4254',
  },
  fonts: {
    regular: 'Manrope_400Regular',
    medium: 'Manrope_500Medium',
    semiBold: 'Manrope_600SemiBold',
    bold: 'Manrope_700Bold',
    extraBold: 'Manrope_800ExtraBold',
  },
  type: {
    display: { fontSize: 32, lineHeight: 39, letterSpacing: -1.1 },
    title: { fontSize: 22, lineHeight: 28, letterSpacing: -0.45 },
    section: { fontSize: 18, lineHeight: 24, letterSpacing: -0.2 },
    body: { fontSize: 15, lineHeight: 22 },
    bodySmall: { fontSize: 13, lineHeight: 19 },
    caption: { fontSize: 12, lineHeight: 17 },
  },
  radius: {
    small: 14,
    medium: 19,
    large: 26,
    hero: 32,
    round: 999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  size: {
    input: 56,
    button: 54,
    iconSmall: 40,
    iconMedium: 48,
  },
  navigation: {
    tabBarHeight: 76,
    tabBarEdgeGap: 9,
    screenContentBottomPadding: 136,
  },
  shadow: {
    card: {
      shadowColor: '#4A4254',
      shadowOpacity: 0.055,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 7 },
      elevation: 1,
    },
    floating: {
      shadowColor: '#4A4254',
      shadowOpacity: 0.12,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 9 },
      elevation: 6,
    },
  },
};
