create table if not exists public.security_audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_user_id uuid references auth.users(id) on delete set null,
  family_id uuid references public.families(id) on delete cascade,
  action text not null check (action in (
    'family_created',
    'invitation_created',
    'invitation_accepted',
    'invitation_revoked',
    'member_removed',
    'child_profiles_changed'
  )),
  target_type text,
  target_id text
);

create index if not exists security_audit_log_family_occurred_idx
on public.security_audit_log(family_id, occurred_at desc);

alter table public.security_audit_log enable row level security;

create or replace function private.authorize_family_access(
  target_family_id uuid,
  target_child_id text default null,
  required_operation text default 'read'
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor_role text;
  child_is_known boolean;
begin
  if (select auth.uid()) is null or target_family_id is null then return false; end if;

  select role into actor_role
  from public.family_members
  where family_id = target_family_id and user_id = (select auth.uid());

  if actor_role is null then return false; end if;

  if target_child_id is not null then
    select exists (
      select 1
      from public.family_states state_row
      cross join lateral jsonb_array_elements(coalesce(state_row.state -> 'children', '[]'::jsonb)) as child(value)
      where state_row.family_id = target_family_id
        and child.value ->> 'id' = target_child_id
    ) into child_is_known;
    if not child_is_known then return false; end if;
  end if;

  if required_operation = 'read' then return true; end if;
  if required_operation = 'write' then return actor_role in ('owner', 'guest'); end if;
  if required_operation = 'manage' then return actor_role = 'owner'; end if;
  return false;
end;
$$;

grant usage on schema private to authenticated;
grant execute on function private.authorize_family_access(uuid, text, text) to authenticated;

create or replace function private.is_family_member(target_family_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.authorize_family_access(target_family_id, null, 'read');
$$;

create or replace function private.is_family_owner(target_family_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.authorize_family_access(target_family_id, null, 'manage');
$$;

grant execute on function private.is_family_member(uuid) to authenticated;
grant execute on function private.is_family_owner(uuid) to authenticated;

create policy "Owners can read security audit logs"
on public.security_audit_log for select to authenticated
using (private.authorize_family_access(family_id, null, 'manage'));

create or replace function private.write_security_audit(
  target_family_id uuid,
  action_name text,
  target_type_value text default null,
  target_id_value text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.authorize_family_access(target_family_id, null, 'read') then return; end if;

  insert into public.security_audit_log(actor_user_id, family_id, action, target_type, target_id)
  values ((select auth.uid()), target_family_id, action_name, target_type_value, target_id_value);
end;
$$;

create or replace function public.authorize_family_operation(
  target_family_id uuid,
  target_child_id text default null,
  required_operation text default 'read'
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.authorize_family_access(target_family_id, target_child_id, required_operation);
$$;

grant execute on function public.authorize_family_operation(uuid, text, text) to authenticated;

create or replace function private.validate_family_state_scope(next_state jsonb)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  field_name text;
begin
  if next_state is null or jsonb_typeof(next_state) <> 'object' then return false; end if;

  foreach field_name in array array['children', 'temperatures', 'medications', 'doctorContacts', 'appointments'] loop
    if jsonb_typeof(coalesce(next_state -> field_name, '[]'::jsonb)) <> 'array' then return false; end if;
  end loop;

  if exists (
    select 1
    from jsonb_array_elements(coalesce(next_state -> 'children', '[]'::jsonb)) as child(value)
    where nullif(child.value ->> 'id', '') is null
  ) then return false; end if;

  if nullif(next_state ->> 'activeChildId', '') is not null
    and not exists (
      select 1
      from jsonb_array_elements(coalesce(next_state -> 'children', '[]'::jsonb)) as child(value)
      where child.value ->> 'id' = next_state ->> 'activeChildId'
    )
  then return false; end if;

  return not exists (
    select 1
    from (
      select value ->> 'childId' as child_id
      from jsonb_array_elements(coalesce(next_state -> 'temperatures', '[]'::jsonb)) as temperature(value)
      union all
      select value ->> 'childId'
      from jsonb_array_elements(coalesce(next_state -> 'medications', '[]'::jsonb)) as medication(value)
      union all
      select value ->> 'childId'
      from jsonb_array_elements(coalesce(next_state -> 'doctorContacts', '[]'::jsonb)) as contact(value)
      union all
      select value ->> 'childId'
      from jsonb_array_elements(coalesce(next_state -> 'appointments', '[]'::jsonb)) as appointment(value)
    ) as references
    where nullif(references.child_id, '') is null
      or not exists (
        select 1
        from jsonb_array_elements(coalesce(next_state -> 'children', '[]'::jsonb)) as child(value)
        where child.value ->> 'id' = references.child_id
      )
  );
end;
$$;

create or replace function public.get_family_state(target_family_id uuid, target_child_id text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result_state jsonb;
begin
  if not private.authorize_family_access(target_family_id, target_child_id, 'read') then
    raise exception 'not authorized';
  end if;

  select state into result_state from public.family_states where family_id = target_family_id;
  return coalesce(result_state, '{}'::jsonb);
end;
$$;

grant execute on function public.get_family_state(uuid, text) to authenticated;

create or replace function public.update_family_state(target_family_id uuid, next_state jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_role text;
  previous_state jsonb;
  children_changed boolean;
begin
  if not private.authorize_family_access(target_family_id, null, 'write')
    or not private.validate_family_state_scope(next_state)
  then
    raise exception 'not authorized';
  end if;

  select role into current_role
  from public.family_members
  where family_id = target_family_id and user_id = (select auth.uid());

  select state into previous_state
  from public.family_states
  where family_id = target_family_id
  for update;

  children_changed := coalesce(previous_state -> 'children', '[]'::jsonb)
    is distinct from coalesce(next_state -> 'children', '[]'::jsonb);

  if current_role = 'guest' and children_changed then raise exception 'not authorized'; end if;

  insert into public.family_states(family_id, state, updated_at, updated_by)
  values (target_family_id, next_state, now(), (select auth.uid()))
  on conflict (family_id) do update
  set state = excluded.state, updated_at = excluded.updated_at, updated_by = excluded.updated_by;

  if children_changed then
    perform private.write_security_audit(target_family_id, 'child_profiles_changed', 'family_state');
  end if;
end;
$$;

grant execute on function public.update_family_state(uuid, jsonb) to authenticated;

create or replace function public.revoke_family_invite(target_invite_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_family_id uuid;
begin
  select family_id into target_family_id
  from public.family_invites
  where id = target_invite_id and status = 'pending';

  if target_family_id is null or not private.authorize_family_access(target_family_id, null, 'manage') then
    raise exception 'not authorized';
  end if;

  update public.family_invites set status = 'revoked' where id = target_invite_id;
  perform private.write_security_audit(target_family_id, 'invitation_revoked', 'family_invite', target_invite_id::text);
end;
$$;

grant execute on function public.revoke_family_invite(uuid) to authenticated;

create or replace function public.remove_family_member(target_family_id uuid, target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.authorize_family_access(target_family_id, null, 'manage')
    or not exists (
      select 1 from public.family_members
      where family_id = target_family_id and user_id = target_user_id and role = 'guest'
    )
  then
    raise exception 'not authorized';
  end if;

  delete from public.family_members
  where family_id = target_family_id and user_id = target_user_id and role = 'guest';
  perform private.write_security_audit(target_family_id, 'member_removed', 'family_member', target_user_id::text);
end;
$$;

grant execute on function public.remove_family_member(uuid, uuid) to authenticated;

create or replace function public.accept_family_invite(invite_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  current_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  target_invite public.family_invites%rowtype;
  current_name text := coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name');
begin
  if current_user_id is null or current_email = '' then raise exception 'not authorized'; end if;

  select * into target_invite
  from public.family_invites
  where id = invite_id and status = 'pending' and expires_at > now()
  for update;

  if target_invite.id is null or lower(target_invite.email) <> current_email then
    raise exception 'not authorized';
  end if;

  insert into public.family_members(family_id, user_id, role, email, display_name)
  values (target_invite.family_id, current_user_id, 'guest', current_email, current_name)
  on conflict (family_id, user_id) do nothing;

  update public.family_invites
  set status = 'accepted', accepted_by = current_user_id
  where id = invite_id;

  perform private.write_security_audit(target_invite.family_id, 'invitation_accepted', 'family_invite', invite_id::text);
  return target_invite.family_id;
end;
$$;

grant execute on function public.accept_family_invite(uuid) to authenticated;
